/* Generated By:JavaCC: Do not edit this line. LispToListsConstants.java */
package mroi.common;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LispToListsConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LPAREN = 5;
  /** RegularExpression Id. */
  int RPAREN = 6;
  /** RegularExpression Id. */
  int DQUOTE = 7;
  /** RegularExpression Id. */
  int ID = 8;
  /** RegularExpression Id. */
  int QUOTED_STRING = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\"\\\"\"",
    "<ID>",
    "<QUOTED_STRING>",
  };

}
